### ISSUE TITLE
enderpearl is not working

### ISSUE THREAD

**Issue by DaddyRobLIVE** [SparklyPower/SparklyPaper#31]
https://github.com/user-attachments/assets/da54e146-1807-4f7a-9da4-dcbf3d550175

watch video

**Comment by DaddyRobLIVE** [comment]
Here's the error log:

`[17:07:43 ERROR]: [ca.spottedleaf.moonrise.common.util.TickThread] Thread serverlevel-tick-worker [world] failed main thread ONLY tick thread check: Cannot change dimension of a player off-main, from world world to world world
java.lang.Throwable: null
        at ca.spottedleaf.moonrise.common.util.TickThread.ensureOnlyTickThread(TickThread.java:96) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-9ac25bc]
        at net.minecraft.server.level.ServerPlayer.changeDimension(ServerPlayer.java:1340) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-9ac25bc]
        at net.minecraft.world.entity.projectile.ThrownEnderpearl.onHit(ThrownEnderpearl.java:74) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-9ac25bc]
        at net.minecraft.world.entity.projectile.Projectile.hitTargetOrDeflectSelf(Projectile.java:239) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-9ac25bc]
        at net.minecraft.world.entity.projectile.Projectile.preHitTargetOrDeflectSelf(Projectile.java:218) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-9ac25bc]
        at net.minecraft.world.entity.projectile.ThrowableProjectile.tick(ThrowableProjectile.java:49) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-9ac25bc]
        at net.minecraft.world.entity.projectile.ThrownEnderpearl.tick(ThrownEnderpearl.java:133) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-9ac25bc]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1256) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-9ac25bc]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:1437) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-9ac25bc]
        at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:745) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-9ac25bc]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:48) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-9ac25bc]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:725) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-9ac25bc]
        at net.minecraft.server.MinecraftServer.lambda$tickChildren$20(MinecraftServer.java:1820) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-9ac25bc]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
[17:07:43 ERROR]: Entity threw exception at world:117.48720085402176,69.05841803818176,-63.780806716644236
java.lang.IllegalStateException: Cannot change dimension of a player off-main, from world world to world world
        at ca.spottedleaf.moonrise.common.util.TickThread.ensureOnlyTickThread(TickThread.java:98) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-9ac25bc]
        at net.minecraft.server.level.ServerPlayer.changeDimension(ServerPlayer.java:1340) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-9ac25bc]
        at net.minecraft.world.entity.projectile.ThrownEnderpearl.onHit(ThrownEnderpearl.java:74) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-9ac25bc]
        at net.minecraft.world.entity.projectile.Projectile.hitTargetOrDeflectSelf(Projectile.java:239) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-9ac25bc]
        at net.minecraft.world.entity.projectile.Projectile.preHitTargetOrDeflectSelf(Projectile.java:218) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-9ac25bc]
        at net.minecraft.world.entity.projectile.ThrowableProjectile.tick(ThrowableProjectile.java:49) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-9ac25bc]
        at net.minecraft.world.entity.projectile.ThrownEnderpearl.tick(ThrownEnderpearl.java:133) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-9ac25bc]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1256) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-9ac25bc]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:1437) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-9ac25bc]
        at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:745) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-9ac25bc]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:48) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-9ac25bc]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:725) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-9ac25bc]
        at net.minecraft.server.MinecraftServer.lambda$tickChildren$20(MinecraftServer.java:1820) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-9ac25bc]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]`
