### ISSUE TITLE
How to fix this error?

### ISSUE THREAD

**Issue by DaddyRobLIVE** [SparklyPower/SparklyPaper#38]
**I get these errors when I regen my resource worlds**

`[10:31:54 ERROR]: [ca.spottedleaf.moonrise.patches.chunk_system.io.RegionFileIOThread$ChunkDataTask] Failed to read chunk data for task: Task for world: 'resource_world' at (-3234,-953) type: ENTITY_DATA, hash: 1343700930
java.nio.channels.ClosedChannelException: null
        at java.base/sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:160) ~[?:?]
        at java.base/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:957) ~[?:?]
        at net.minecraft.world.level.chunk.storage.RegionFile.getChunkDataInputStream(RegionFile.java:575) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-8c40f73]
        at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:223) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-8c40f73]
        at ca.spottedleaf.moonrise.patches.chunk_system.io.datacontroller.EntityDataController.readData(EntityDataController.java:33) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-8c40f73]
        at ca.spottedleaf.moonrise.patches.chunk_system.io.RegionFileIOThread$ChunkDataTask.run(RegionFileIOThread.java:1166) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-8c40f73]
        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue$PrioritisedTask.executeInternal(PrioritisedThreadedTaskQueue.java:351) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-8c40f73]
        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue.executeTask(PrioritisedThreadedTaskQueue.java:118) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-8c40f73]
        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.pollTasks(PrioritisedQueueExecutorThread.java:114) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-8c40f73]
        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:50) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-8c40f73]`

**Comment by MrPowerGamerBR** [comment]
How are you regenerating your worlds? I'm pretty sure that this is not a SparklyPaper issue and that this same error would also happen in vanilla Paper

**Comment by DaddyRobLIVE** [comment]
I'm using multiverse to regen. I use /mvregen. I tried doing something else
like /mvdelete then /mvcreate but it does this.

I also tried switching vanilla and this doesn't happen there.
