### ISSUE TITLE
Missing entities after pasting FAWE

### ISSUE THREAD

**Issue by DaddyRobLIVE** [SparklyPower/SparklyPaper#44]
I'm moving villagers to another area but they disappear and I got this error below

```
[11:18:08 ERROR]: [ca.spottedleaf.moonrise.common.util.TickThread] Thread serverlevel-tick-worker [trading] failed main thread check: Accessing poi chunk off-main @ world kalayaan chunkX: -1383 chunkZ: 936 - Is tick thread? true; Is server level tick thread? true; Currently ticking level: trading; Is iterating over levels? true; Are we going to hard throw? true
java.lang.Throwable: null
        at ca.spottedleaf.moonrise.common.util.TickThread.ensureTickThread(TickThread.java:49) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-aeb7b1c]
        at net.minecraft.world.entity.ai.village.poi.PoiManager.getOrLoad(PoiManager.java:88) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-aeb7b1c]
        at net.minecraft.world.entity.ai.village.poi.PoiManager.getType(PoiManager.java:352) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-aeb7b1c]
        at net.minecraft.world.entity.npc.Villager.lambda$releasePoi$7(Villager.java:728) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-aeb7b1c]
        at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at net.minecraft.world.entity.npc.Villager.releasePoi(Villager.java:723) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-aeb7b1c]
        at net.minecraft.world.entity.ai.behavior.SetWalkTargetFromBlockMemory.lambda$create$0(SetWalkTargetFromBlockMemory.java:46) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-aeb7b1c]
        at net.minecraft.world.entity.ai.behavior.declarative.BehaviorBuilder$1.trigger(BehaviorBuilder.java:42) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-aeb7b1c]
        at net.minecraft.world.entity.ai.behavior.OneShot.tryStart(OneShot.java:17) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-aeb7b1c]
        at net.minecraft.world.entity.ai.Brain.startEachNonRunningBehavior(Brain.java:443) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-aeb7b1c]
        at net.minecraft.world.entity.ai.Brain.tick(Brain.java:403) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-aeb7b1c]
        at net.minecraft.world.entity.npc.Villager.customServerAiStep(Villager.java:258) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-aeb7b1c]
        at net.minecraft.world.entity.npc.Villager.customServerAiStep(Villager.java:253) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-aeb7b1c]
        at net.minecraft.world.entity.npc.Villager.inactiveTick(Villager.java:237) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-aeb7b1c]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1258) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-aeb7b1c]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:1437) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-aeb7b1c]
        at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:745) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-aeb7b1c]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:48) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-aeb7b1c]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:725) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-aeb7b1c]
        at net.minecraft.server.MinecraftServer.lambda$tickChildren$20(MinecraftServer.java:1818) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-aeb7b1c]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[11:18:08 ERROR]: Entity threw exception at trading:76.30000001192093,21.30000001192093,350.30000001192093
java.lang.IllegalStateException: Accessing poi chunk off-main
        at ca.spottedleaf.moonrise.common.util.TickThread.ensureTickThread(TickThread.java:51) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-aeb7b1c]
        at net.minecraft.world.entity.ai.village.poi.PoiManager.getOrLoad(PoiManager.java:88) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-aeb7b1c]
        at net.minecraft.world.entity.ai.village.poi.PoiManager.getType(PoiManager.java:352) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-aeb7b1c]
        at net.minecraft.world.entity.npc.Villager.lambda$releasePoi$7(Villager.java:728) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-aeb7b1c]
        at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at net.minecraft.world.entity.npc.Villager.releasePoi(Villager.java:723) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-aeb7b1c]
        at net.minecraft.world.entity.ai.behavior.SetWalkTargetFromBlockMemory.lambda$create$0(SetWalkTargetFromBlockMemory.java:46) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-aeb7b1c]
        at net.minecraft.world.entity.ai.behavior.declarative.BehaviorBuilder$1.trigger(BehaviorBuilder.java:42) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-aeb7b1c]
        at net.minecraft.world.entity.ai.behavior.OneShot.tryStart(OneShot.java:17) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-aeb7b1c]
        at net.minecraft.world.entity.ai.Brain.startEachNonRunningBehavior(Brain.java:443) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-aeb7b1c]
        at net.minecraft.world.entity.ai.Brain.tick(Brain.java:403) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-aeb7b1c]
        at net.minecraft.world.entity.npc.Villager.customServerAiStep(Villager.java:258) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-aeb7b1c]
        at net.minecraft.world.entity.npc.Villager.customServerAiStep(Villager.java:253) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-aeb7b1c]
        at net.minecraft.world.entity.npc.Villager.inactiveTick(Villager.java:237) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-aeb7b1c]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1258) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-aeb7b1c]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:1437) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-aeb7b1c]
        at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:745) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-aeb7b1c]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:48) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-aeb7b1c]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:725) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-aeb7b1c]
        at net.minecraft.server.MinecraftServer.lambda$tickChildren$20(MinecraftServer.java:1818) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-aeb7b1c]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

```

**Comment by Godl1nk** [comment]
![image](https://github.com/user-attachments/assets/7c4f0b73-2a62-44b6-b610-62273516e968)
solve yourself by posting the method back to world thread

**Comment by DaddyRobLIVE** [comment]
How do I do that? I don't develop plugin.

**Comment by Godl1nk** [comment]
er u edit the source code or spam SparklyPaper to fix it

**Comment by DaddyRobLIVE** [comment]
Sorry. I'm not yet knowledgeable with that :(

**Comment by Godl1nk** [comment]
if need urgent maybe pm me discord .godl1nk

**Comment by DaddyRobLIVE** [comment]
Okay, I DMed you!
